name: pipeline
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    name: Unit Tests (PHP Unit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use composer cache if possible
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.0.8
          php_extensions: pdo_pgsql soap gd zip

      - name: Run tests
        run: |
          composer test

  static_code_analysis:
    name: Static Code Analysis (Psalm)
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use composer cache if possible
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.0.8
          php_extensions: pdo_pgsql soap gd zip

      - name: Run static code
        run: |
          composer analysis

  lint:
    name: Linting (PHP CS Fixer)
    runs-on: ubuntu-latest
    needs: [static_code_analysis]
    steps:
      - uses: actions/checkout@v2
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=./.php-cs-fixer-dist.php --stop-on-violation --show-progress=dots -vvv
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
